### ISSUE TITLE
Improve cp curve solver

### ISSUE THREAD

**Issue by lpwoolcock** [lpwoolcock/turbine-eor#4]
- Make it work for region 3
- Make it use "fzero" instead of newton's method

**Comment by VincentLiu92168** [comment]
Edited in observer blocks
Nothing much needs to change for Region 3:
- Monotonicity issue disappears beyond certain pitch values
- Scheme can become: use previous lambda as the starting guess x0, else use optimal lambda for theta = 0 i.e lambda_star approx 7.5
